import { Link } from "expo-router";
import { ScrollView, Text } from "react-native";

export default function About() {
  return (
    <ScrollView>
      <Link href='/'>Regresar</Link>
      <Text className='text-white font-bold mb-8 text-2xl'>Sobre el proyecto</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
      <Text className='text-white/90'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque sapiente suscipit quas obcaecati quasi expedita tempore quaerat dolorem consequatur dignissimos? Sed aliquid beatae officiis nobis corrupti, deleniti cupiditate laudantium molestias!</Text>
    </ScrollView>
  )
}